x-var: &APP_NAME
 wp_share_post_slug

services:
  wpdb:
    image: mariadb
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: *APP_NAME
      MYSQL_DATABASE: *APP_NAME
      MYSQL_USER: *APP_NAME
      MYSQL_PASSWORD: *APP_NAME
    expose:
      - 3306
      - 33060
    healthcheck:
      test: mariadb-admin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55
  wpcli:
    image: wordpress:cli
    depends_on:
      wordpress:
        condition: service_started
      wpdb:
        condition: service_healthy
    user: www-data:www-data
    command: wp core install --url=localhost:8080 --title=WPDev --admin_user=admin --admin_password=admin --admin_email=admin@example.com
    volumes:
      - wp_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: wpdb
      WORDPRESS_DB_USER: *APP_NAME
      WORDPRESS_DB_PASSWORD: *APP_NAME
      WORDPRESS_DB_NAME: *APP_NAME
  wordpress:
    image: automattic/wordpress-xdebug
    volumes:
      - wp_data:/var/www/html:rw
      - ./themes:/var/www/html/wp-content/themes/:rw
      - ./plugins:/var/www/html/wp-content/plugins/:rw
      - ./conf.d/local.ini:/usr/local/etc/php/conf.d/xdebug.ini
    ports:
      - 8080:80
    environment:
      XDEBUG_PORT: 9003
      WORDPRESS_DB_HOST: wpdb
      WORDPRESS_DB_USER: *APP_NAME
      WORDPRESS_DB_PASSWORD: *APP_NAME
      WORDPRESS_DB_NAME: *APP_NAME
      WORDPRESS_CONFIG_EXTRA: |
        define( 'DOCKER_LOCAL_DEVELOPMENT', true );
volumes:
  db_data:
  wp_data:
